AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  JiraDomainParam:
    Type: String
    Description: "Dominio de Jira (por ejemplo: mycompany.atlassian.net)"
  JiraUserParam:
    Type: String
    Description: "Usuario de Jira (email)"
  JiraApiTokenParam:
    Type: String
    Description: "Token/API de Jira"
  OutputS3BucketParam:
    Type: String
    Description: "Nombre del bucket S3 donde se subirá el reporte Excel"

Globals:
  Function:
    Runtime: python3.10
    Timeout: 60
    MemorySize: 128

Resources:

  # -----------------------------------------------------------------
  # 1) DEFINICIÓN DEL LAYER: aquí van SOLO las dependencias pip-minimas
  # -----------------------------------------------------------------
  ValidarHUFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ValidarHUFunctionLayer
      Description: "Layer con dependencias Python (jira, spacy, openpyxl)"
      ContentUri: my-layers/           # <-- apunta a la carpeta que contiene "python/"
      CompatibleRuntimes:
        - python3.10

  # -----------------------------------------------------------------
  # 2) DEFINICIÓN DE LA FUNCIÓN LAMBDA: apuntando solo a hello_world/
  # -----------------------------------------------------------------
  ValidarHUFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ValidarHUFunction
      Handler: app.lambda_handler
      CodeUri: hello_world/            # <-- SOLO tu código, sin deps grandes
      Layers:
        - !Ref ValidarHUFunctionLayer   # <-- inyecta el layer con las libs
      Environment:
        Variables:
          JIRA_DOMAIN:      !Ref JiraDomainParam
          JIRA_USER:        !Ref JiraUserParam
          JIRA_API_TOKEN:   !Ref JiraApiTokenParam
          OUTPUT_S3_BUCKET: !Ref OutputS3BucketParam
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  ApiUrl:
    Description: "URL de API Gateway para invocar la Lambda"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ValidarHUFunctionArn:
    Description: "ARN de la función ValidarHUFunction"
    Value: !GetAtt ValidarHUFunction.Arn
