AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  JiraDomainParam:
    Type: String
  JiraUserParam:
    Type: String
  JiraApiTokenParam:
    Type: String
  OutputS3BucketParam:
    Type: String

Resources:

  # ───────────────────────────────────────────────────────────
  # 1) Declaramos el layer como recurso SAM: AWS::Serverless::LayerVersion
  # ───────────────────────────────────────────────────────────
  ValidarHUFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ValidarHUFunctionLayer
      Description: "Dependencias Python para ValidarHU (spaCy, jira, openpyxl, etc.)"
      ContentUri: my-layers/python/       # <-- aquí va tu carpeta “python/” con las deps ya recortadas
      CompatibleRuntimes:
        - python3.10

  # ───────────────────────────────────────────────────────────
  # 2) Definimos la función Lambda que referenciará solo al layer
  # ───────────────────────────────────────────────────────────
  ValidarHUFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ValidarHUFunction
      Handler: app.lambda_handler
      Runtime: python3.10
      CodeUri: hello_world/               # <-- aquí solo tu código (sin deps pesadas)
      MemorySize: 128
      Timeout: 60
      Layers:
        - !Ref ValidarHUFunctionLayer      # <-- el layer declarado arriba
      Environment:
        Variables:
          JIRA_DOMAIN: !Ref JiraDomainParam
          JIRA_USER:   !Ref JiraUserParam
          JIRA_API_TOKEN: !Ref JiraApiTokenParam
          OUTPUT_S3_BUCKET: !Ref OutputS3BucketParam
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway URL para llamar a la Lambda"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunctionArn:
    Description: "ARN de la función Lambda"
    Value: !GetAtt ValidarHUFunction.Arn
