AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Mi plantilla SAM con función y layer.

Globals:
  Function:
    Runtime: python3.9
    Timeout: 60
    MemorySize: 128

Resources:

  ## 1) LayerVersion para librerías comunes o módulos compartidos
  ValidarHUFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ValidarHUFunctionLayer
      Description: "Módulos Python compartidos para ValidarHUFunction"
      ContentUri: layer/            # SAM tomará todo el contenido de esa carpeta y lo zippea
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: "MIT"

  ## 2) La función Lambda que usa ese layer
  ValidarHUFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ValidarHUFunction
      Handler: app.lambda_handler
      CodeUri: hello_world/         # Carpeta donde está tu app.py y demás requisitos
      Layers:
        - !Ref ValidarHUFunctionLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref OutputS3Bucket
      Environment:
        Variables:
          JIRA_DOMAIN:     !Ref JiraDomainParam
          JIRA_USER:       !Ref JiraUserParam
          JIRA_API_TOKEN:  !Ref JiraApiTokenParam
          OUTPUT_S3_BUCKET: !Ref OutputS3Bucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /validar
            Method: get

Parameters:
  JiraDomainParam:
    Type: String
    Description: "Dominio Jira (p.ej. miempresa.atlassian.net)"
  JiraUserParam:
    Type: String
    Description: "Usuario Jira (correo o user)"
  JiraApiTokenParam:
    Type: String
    Description: "API token de Jira"
  OutputS3Bucket:
    Type: String
    Description: "Nombre del bucket S3 donde subir los reportes"
