AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Plantilla SAM para ValidarHU empaquetada como imagen Docker Python 3.10"

Globals:
  Function:
    Timeout: 900       # 15 minutos
    MemorySize: 1024

Resources:

  ###################################
  # Función empaquetada como imagen
  ###################################
  ValidarHUFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ValidarHUFunction
      PackageType: Image
      ImageUri: validarhu-lambda:latest
      ImageConfig:
        Command: ["app.lambda_handler"]
      Environment:
        Variables:
          JIRA_DOMAIN:      !Ref JiraDomainParam
          JIRA_USER:        !Ref JiraUserParam
          JIRA_API_TOKEN:   !Ref JiraApiTokenParam
          OUTPUT_S3_BUCKET: !Ref OutputS3Bucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref OutputS3Bucket

Parameters:
  JiraDomainParam:
    Type: String
    Description: "Dominio de Jira (p.ej. miempresa.atlassian.net)"
  JiraUserParam:
    Type: String
    Description: "Usuario de Jira (email)"
  JiraApiTokenParam:
    Type: String
    Description: "API token de Jira"
  OutputS3Bucket:
    Type: String
    Description: "Bucket S3 donde subiremos los reportes"
