AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  JiraDomainParam:
    Type: String
  JiraUserParam:
    Type: String
  JiraApiTokenParam:
    Type: String
  OutputS3BucketParam:
    Type: String

Resources:

  # -----------------------------------------
  # 1) Definimos el layer “ValidarHUFunctionLayer”
  # -----------------------------------------
  ValidarHUFunctionLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: validarhu-layer-minimo
      Description: "Layer mínimo con spaCy + jira + openpyxl"
      Content:
        # Aquí referenciamos el ZIP que acabamos de crear
        ZipFile: my-layers/lambda-layer-minimo.zip
      CompatibleRuntimes:
        - python3.10

  # -----------------------------------------
  # 2) Definimos la función Lambda “ValidarHUFunction”
  # -----------------------------------------
  ValidarHUFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ValidarHUFunction
      Handler: app.lambda_handler
      Runtime: python3.10
      CodeUri: hello_world/
      MemorySize: 128
      Timeout: 60
      Layers:
        - !Ref ValidarHUFunctionLayer
      Environment:
        Variables:
          JIRA_DOMAIN: !Ref JiraDomainParam
          JIRA_USER: !Ref JiraUserParam
          JIRA_API_TOKEN: !Ref JiraApiTokenParam
          OUTPUT_S3_BUCKET: !Ref OutputS3BucketParam
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway URL para llamar a la Lambda"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunctionArn:
    Description: "ARN de la función Lambda"
    Value: !GetAtt ValidarHUFunction.Arn
