AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  JiraDomainParam:
    Type: String
  JiraUserParam:
    Type: String
  JiraApiTokenParam:
    Type: String
  OutputS3BucketParam:
    Type: String

Resources:

  ValidarHUFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: validar-hu-python-deps
      Description: "Dependencias Python (pandas, jira, openpyxl, spacy, jinja2, etc.)"
      ContentUri: lambda-layer-core.zip      # ← Apunta al ZIP que generaste
      CompatibleRuntimes:
        - python3.10

  ValidarHUFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ValidarHUFunction
      Handler: app.lambda_handler
      Runtime: python3.10
      CodeUri: hello_world/                 # tu carpeta con app.py y lógica
      Layers:
        - !Ref ValidarHUFunctionLayer
      Environment:
        Variables:
          JIRA_DOMAIN: !Ref JiraDomainParam
          JIRA_USER: !Ref JiraUserParam
          JIRA_API_TOKEN: !Ref JiraApiTokenParam
          OUTPUT_S3_BUCKET: !Ref OutputS3BucketParam
      Timeout: 300
      MemorySize: 512

Outputs:
  ValidarHUFunctionArn:
    Description: "ARN de la función Lambda"
    Value: !GetAtt ValidarHUFunction.Arn

  ValidarHUFunctionLayerArn:
    Description: "ARN de la capa de dependencias"
    Value: !Ref ValidarHUFunctionLayer
